[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
indexer_example = "8kwhCLtDn37GDLYPWdCTyPSVyi8fUdq5x3X7PhFCnxEV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
